# Generated by Django 3.0.8 on 2020-07-30 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200730_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numeric Characters are allowed!')]),
        ),
    ]
