# Generated by Django 3.0.8 on 2020-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200730_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_profile_friends_+', to='myapp.Profile'),
        ),
    ]
